### ISSUE TITLE
Motor Drivers Dying

### ISSUE THREAD

**Issue by PavloNikitiuk07** [tobbelobb/hangprinter#12]
Hey! I've been trying to assemle your printer, but ran into one big issue. My motor drivers (DRV8825) constantly die. 
I've tried cooling them with an extenal fan, which does prolong their lifecycle, but they still keep on dying on me.

How many amps do you send to the motors?
Can you give me any suggestions?

**Comment by tobbelobb** [comment]
With so little info I can just guess that you don't tune your driver correctly, that you unplug motors while running, that your RAMPS is damaged or that something else is electrically wrong in your setup.

Try web search like for example:
https://duckduckgo.com/?q=DRV8825+dying+site%3Aforums.reprap.org

Or other relevant references like:
http://reprap.org/wiki/DRV8825
http://reprap.org/wiki/A4988_vs_DRV8825_Chinese_Stepper_Driver_Boards
https://www.pololu.com/product/2132/

Or if you need an intro to stepstick usage in general:
http://www.instructables.com/id/Drive-a-Stepper-Motor-with-an-Arduino-and-a-A4988-/

I'm closing since improving and debugging drv8825s is outside the scope of this repo.

Best regards
