### ISSUE TITLE
Moving the movement steppers to the mounting points

### ISSUE THREAD

**Issue by twikis** [tobbelobb/hangprinter#5]
Hi Tobben!

Thank you very much for this amazing work, I just ordered the Vitamins for the printer and I'm going to print out the parts very soon.

Here's a thing: a few interested people and me are wondering why you haven't/aren't moving the movement steppers to the mounting points, in order to save weight on the printing head? This would save 600-750g (of course depending on the steppers used) on the print head, allowing for much higher accuracy, resolution, acceleration and speeds. The two simplest ways for doing this I can see are:
1. Taking the RAMPS out of the print head and putting it on the ground, then feeding the 8 stepper wires (D-Lines and extruder) +heater cartridge, fan and temperature sensor (maybe use a coax cable or amplifier to avoid interference) from the ground RAMPS to the print head and the stationary mounted steppers.
2. Leaving the RAMPS on the print head/moving it to a ground station and routing the stepper driver lines to dedicated stepper drivers mounted on a base station/the print head, depending on which version makes more sense. Pro: much less wires to take care off | Con: much more complicated

I understand that this will make the whole printer less compact and split it up in multiple parts, thereby making it less of a beauty, but I do think it's worth it when thinking about the speeds that could be archieved. Which is on the other hand making it much more attractive to everyone. How about a second brach for "enthusiasts"?

Alternatively you could of course gear down the motors for smaller stepper motors, as the rpm limit of steppers isn't even closely reached (unfortunately I don't have the skills to design this myself, otherwise I would).

Another thing we have come across: We've been thinking that much smaller motors may be sufficient for the D-Lines and extruder, thereby saving another few valuable grams. Could you provide any numbers regarding neccessary N/cm? Maybe by trying out how low you can go on current on the motors?

Greetings!

Matthias

PS. We've created a facebook group for the Hangprinter, you can find it here: https://www.facebook.com/groups/176856636157837

**Comment by RigTig** [comment]
Matthias, there is a design (work-in-progress) using motors at the supports (see https://hackaday.io/project/13420-rigtigs-big-3d-printer) and it has been done several times before too. And the steppers are really light too. BUT, cabling is a pain especially when you want to adapt or move the support nodes. In fact, I started with cables to each node and found it far too awkward to set up each time, so I am now trying to use a local wifi network. 
Besides, using long cables for high-current purposes is a poor design choice, made worse when you consider the effects from rapid off-on cycles (slower ramping speeds and power losses).

You said that you are: 
> allowing for much higher accuracy, resolution, acceleration and speeds

but what accuracy, resolution, acceleration and speeds do you need when working at much greater scale than a desktop 3D printer. I've decided that for a 10 metre length of printing, a 2mm resolution is very acceptable (0.02%). And the speed needs to match the material being 'extruded'; note that clay can be pumped only so fast anyway. Assuming that accuracy refers to reproducibility, then the variation caused by the material is probably much higher than the effector location anyway. Anyway, this rant is really about choosing a desired outcome based on practicality rather than just pushing limits for the sake of pushing them.
If you or others are so keen on another branch, then just create a fork and go for it.

Tobben, I reckon you have achieved something quite amazing. Your whole printer fits into a bucket or backpack for transport and yet can print very large objects upon installation. Once I have finished this iteration of my own 3D printer, I am going to have a go at putting all the motors on the effector (as you have successfully done). I wish I had thought of it myself, since communicating with the remotely positioned motors has been the core of the issues with my approach. At least I have learnt a lot in the process of getting this far.

**Comment by tobbelobb** [comment]
ABCD motors + RAMPS can be mounted in the ceiling (near the D-anchor points). Dynema lines can be routed such that firmware and worm drive can remain unchanged. Routing for A-lines would be like this:
D-anchor --> A-anchor --> A-action
An action point is a point where a line meets the moving unit.
All credz for this idea goes to Alexander Osika.

I strongly prefer constant length stepper cables.

Your comments and gearing down and downsizing motors are correct. Hangprinter in its current shape needs only ca 1 Ncm of torque. A Nema14 version should be possible, although less forgiving about pull from power cables and such.

Haha, the master branch is already for crazy enthusiasts. I'm still waiting for the first functional copy (other than my own) to appear. I'll make a branch as soon as I start developing a stationary-ABCD-motors version =)

RigTig: I'm really happy about any cross-pollination of our projects =)

**Comment by twikis** [comment]
@RigTig Thank you for your answer, you're right I haven't read much about frameless printers other than the Hangprinter.
Thank you for explaining a bit about your printer!

Mate, I don't know why you're taking this personal or why you think it's necessary to play this up but so be it. Your rant is noted lol. I believe I've been respectful and don't care what you're making out of my suggestion to be honest.
Let's keep the positive spirit alive, okay?

Regarding reproducibility: What I mean are differences from one layer to another layer, those are just ruining every print. Same goes for wobble/ringing/ghosting and similar.
I agree with you that 2mm/10m accuracy are definitely sufficient.

And just think about it, wouldn't it be cool if the Hangprinter could also be used as a pretty good desktop 3D printer by only replacing the hotend? Just saying because I believe there's quite some potential in this.

@ Tobben thank you for your explanations! You mention that the Hangprinter needs less than 1 N/cm of force, so even the smallest NEMA14 should be enough and there are NEMA14s with 7 N/cm that weigh 50g. As the printer is becoming much lighter with lighter motors, even less is torque is needed as well. I believe the results could be worth it. Alternatively one could just use thicker dyneema lines, but that would also mean thicker spools... What diameter are you recommending/are you using by the way?

Alexander Osikas idea is great. The only drawback I can see is that the dynema lines will be a bit longer. Nice! Really looking forward to seeing qhat stationary ABCD version will be capable of.

I hope I can get it to work! Where do you think is the best place to post any questions and build notes so that other people can profit from them later on?

**Comment by tobbelobb** [comment]
Sorry, the 1 Ncm was a brainfart. The motors need 15-20 Ncm in the current design. I've written about it [here](http://www.vitana.se/opr3d/tbear/2015.html#hangprinter_project_7) and [here](http://www.vitana.se/opr3d/tbear/#hangprinter_project_27)

Technical questions (that are not clearly bugs/issues with the design) are best posted here: forums.reprap.org/read.php?1,738858,758075
For build notes, choose whatever format you're comfortable with. Openbuilds, Hackaday and the RepRap wiki are all great.

**Comment by Tesla3DTore** [comment]
Hi everybody,

Very good idea how to remove stepper to ground or ceil point...

https://youtu.be/sytyQvUXN8Q

So I thing a mix with that and the hangprinter will be the best..

I almost finish to print the part so I will be the first clone of hangprinter.. pictures and videos will follow for the end of this week...,
